#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-bigblow.setup
#+OPTIONS: toc:nil num:nil html-style:nil
#+Title: OnDemand Notes
#+TOC: headlines 1
* Useful Phone Numbers
  :PROPERTIES:
  :CUSTOM_ID: TargetSection
  :END:
  CONTENTS
#+TOC: headlines 1 local :target #TargetSection
** Registration
   Identify self as NYP OnDemand provider, ask for person who is handling registrations. Be ready w name, DOB, address, phone, complaint
   - weekdays:  (646) 697-0460
   - weekend:   (212) 746-4250
   - after 8pm: (212) 746-0604
** <<erContacts>> NYC Emergency Dept. Numbers
*** ADULT ERs
**** MANHATTAN
    - NYP –Weill Cornell Medicine 212-746-3701
    - NYP –Columbia / Milstein 212-305-6204
    - NYP –Allen Pavilion 212-932-4245
    - NYP –Lower Manhattan Hospital 212-312-5701
    - Mt. Sinai (UES)212-241-6639
    - Mt. Sinai –Beth Israel 212-420-2840
    - Mt. Sinai West / St. Lukes 212-523-4000
    - NYU –Bellevue 212-562-8052
    - Harlem Hospital Center 212-939-2250
**** QUEENS
    - NYP –Queens 718-670-1100
    - Flushing Hospital Medical Center 718-670-5495
    - Mt. Sinai -Elmhurst 718-334-3054
    - Mt. Sinai –Hospital of Queens (LIC/Astoria)718-932-1000
    - Northwell –LIJ 718-470-7500
**** BROOKLYN
    - NYP –Brooklyn Methodist 718-780-5555
    - Coney Island Hospital347-563-6552
    - SUNY –King’s County Hospital 718-245-4602 / 718-270-6315
    - Woodhull Hospital 718-963-8442
    - Maimonides Medical Center 718-283-1434
**** BRONX
    - Jacobi Medical Center 718-918-5800
    - Lincoln Hospital 718-579-5200
    - SBH Health System(St. Barnabas)718-960-9000 (connect to ER)
    - North Central Bronx Hospital 718-519-3013
    - Montefiore Medical Center 718-920-5731
*** PEDS ERs
**** MANHATTAN
    - NYP –Weill Cornell Medicine 212-746-3300
    - NYP –Morgan Stanley/CHONY 212-305-6628
    - NYP –Lower Manhattan Hospital 212-312-5059
    - Mt. Sinai (UES)–Kravis Children’s 212-241-7151
    - Mt. Sinai –Beth Israel 212-420-2860
    - NYU –Hassenfeld Children’s Hospital 646-341-2470/ 212-263-5550
    - Harlem Hospital Center 212-939-2250
**** QUEENS
    - NYP –Queens 718-670-1947
    - Flushing Hospital Medical Center 718-670-5495
    - Mt. Sinai -Elmhurst 718-334-3054
    - Northwell –Cohen’s 718-470-7500
**** BROOKLYN
    - NYP –Brooklyn Methodist 718-780-5555
    - Coney Island Hospital347-563-6552
    - SUNY –King’s County Hospital 718-245-4602
    - Maimonides Medical Center 718-283-7230
**** BRONX
    - Jacobi Medical Center 718-918-5875
    - Lincoln Hospital 718-579-5200
    - SBH Health System(St. Barnabas) 718-960-9000 (connect to ER)
    - North Central Bronx 718-519-3015
    - Montefiore Medical Center –CHAM 718-741-2150
** Pacific Interpreters
   - (800) 876-3059, code=836970
** NYP Cornell Work Health Safety (WHS)
   - 646-697-9470.
** Referrals (see [[referralTarget][referrals section]])
* <<referralTarget>> Referrals and Follow up
  CONTENTS
#+TOC: headlines 1 local
** PA follow up for at-risk, symptomatic COVID patients at home:
   email the patient's name, MRN, DOB and phone number to CovidTeleFollowUP@med.cornell.edu, give patients their number 212 746 3262
** Coupons
   April2020, Adult: WCEA59042, Peds: WCEP10467
** Specialty Referrals
*** Cardiology
    - 646 962 5558
*** Dermatology
    - (646) 962-3376
*** ENT
    - 646 962 3681
*** GI
    - 646 962 8462
*** OB/GYN
    - 646 962 2229
*** Ophthalmology
    - 646 962 2020
*** Ortho
    - 212 746 1500
*** Primary Care
    - 646 962 7300
*** Psychiatry/Mental Health
    - google 'virtual mental health'
    - 888 NYC WELL or
    - Text WELL to 65173
    - Access Service (all Presbyterian Mental Health Services) 888 694 5700
    - Specialty Center (faculty on 62nd St): 646 962 2820
    - Physicians' Organization (private pay): 888 694 2255
*** Pulmonary and Critical Care
    - 646 962 2333
*** Rehab Medicine/Sports/Ortho/Spine
    - 212 746 1500
*** Rheumatology
    - 877 606 1555
*** Urology
    - 646 962 9600
*** Vascular Surgery
    - 646 962 8450
* Situations
  CONTENTS
#+TOC: headlines 1 local
** Patients Heading to ER:
*** What to tell patients:
    - Do not take public transportation
    - if taking cab, wear mask, with windows open
    - You may NOT have visitors at hospital
    - Have your emergency contact info available
    - Bring medication list
    - and problem list
    - If patient does not speak English, help family member to write letter
*** Do warm hand off to ED: [[erContacts][NYC Emergency Dept Contact Numbers]]
** Need to call 911
   - if calling from within hospital, you may need operator or security (746 0911) to dial 911
   - tell patient to unlock door
   - wait with patient for EMS to arrive
   - figure out with EMS which hospital patient is going to
   - give warm hand-off to that ER. [[erContacts][NYC Emergency Room Contacts]]
** Hospital Employees
   - see [[covidFAQ][OnDemand COVID FAQ]]
* Software/Technical
  CONTENTS
#+TOC: headlines 1 local
** Adding Telehealth Lists to AllScripts
   - [[file:addingListToAllScripts.docx][instructions]]
* Chief Complaints
  CONTENTS
#+TOC: headlines 1 local
** Covid and covid-like sx................................................................................
    CONTENTS
  #+TOC: headlines 1 local
*** Dyspnea Exam
    - [[https://drive.google.com/file/d/1Y18crrFOhJucIOZEYK3CYa2rYyuQTiK3/view][COVID19 Respiratory Reassessment - benign exam video]]
    - [[https://drive.google.com/file/d/1-zWOYfQqBwN8WN0j5YUOS8SqQxpCRkDg/view][COVID19 Respiratory Reassessment - severe exam video]]
*** <<isolationInstructionsTarget>> Home Isolation Instructions
    *GENERAL COVID-19 HOME ISOLATION DISCHARGE INSTRUCTION*

    Based on the evaluation from our telemedicine visit, you have symptoms most likely consistent with COVID-19. Please read the following instructions carefully and initiate home isolation immediately. 

    Seek prompt medical attention if your illness is worsening, such as if you are having difficulty breathing, feel short of breath or have chest pain when you move around normally at home, are unable to speak in full sentences without having to stop because you are winded, or have fewer than two urinations a day or other concerning symptoms. Put on a facemask before you enter any medical facility. These steps will help the medical facility keep other people from getting infected or exposed.

    If you believe you have a medical emergency, call 911 and notify the dispatcher that you have or are being evaluated for COVID-19. Put on a facemask before emergency medical services arrive.

    Symptoms may last as long as 1-2 weeks depending on your age and other health conditions that you may have.  

    ***SELF-CARE INSTRUCTIONS***
    - Rest as much as possible. Slowly start to do more each day.
    - You can take acetaminophen (Tylenol) as per the instruction on the label for fever, body aches, cough, or headaches.
    - Drink more liquids as directed to help thin and loosen mucus so it is easier to cough up. Liquids such as water, fruit juice, and broth also help keep you hydrated.
    - Soothe a sore throat by gargling with warm salt water. Make salt water by dissolving ¼ teaspoon salt in 1 cup warm water. Older children and adults can also use throat lozenges, ice chips, or sore throat spray.
    - Use a humidifier or vaporizer to increase air moisture in your home. This may make it easier to breathe and help decrease coughing.
    - Use saline nasal drops as directed to relieve congestion.
    - Apply petroleum-based jelly around the outside of nostrils to decrease irritation from blowing your nose.
    - Do not smoke. Nicotine and other chemicals in cigarettes and cigars can make your symptoms worse.
    - Do not vape.

    ***HOME ISOLATION INSTRUCTIONS***
    STAY HOME except to get medical care:
    - Do not go outside at all, either to work, school, or public areas, such as stores or movie theaters.
    - Do not use public transportation. If you have to take a car, wear a mask and leave the window open.
    - Separate yourself from other people and pets in your home. Stay in a separate bedroom and use a separate bathroom, if available.
    - Ask others to care for your animals.
    - Wear a facemask when around other people or pets.
    - Cover your coughs and sneezes with a tissue. Throw tissues away in trashcan lined with a plastic bag and clean your hands after you throw away the tissue.
    - Clean your hands often with soap and water (for 20 seconds) or with hand sanitizer containing 60% to 95% alcohol. If using hand sanitizer with alcohol, cover all surfaces of your hands and rub hands together until they feel dry.
    - Use soap and water if your hands are visibly dirty.
    - Avoid touching your eyes, nose, and mouth. Clean your hands if you do touch your face.
    - Do not share household items including cups, plates, eating utensils, towels, bedding, or clothes with other people or pets. After you use these items, wash them thoroughly with soap and water. 
    - Clean “high-touch” surfaces each day such as counters, tabletops, doorknobs, bathroom fixtures, toilets, phones, keyboards, tablets, and bedside tables.
    - Clean any surfaces that have blood, stool, or body fluids on them.
    - Use household cleaning spray or wipe, according to the label instructions. Read cleaning product label instructions for safe and effective use of the cleaning product.

    ***WHEN TO DISCONTINUE HOME ISOLATION***
    When you have had no fever for at least 72 hours (that is three full days of no fever without the use medicine that reduces fevers) AND other symptoms have improved AND at least 7 days have passed since your symptoms first appeared.

    ***FOR MORE INFORMATION***
    - Discuss any additional questions with your healthcare provider.
    - Visit the CDC website at www.cdc.gov
    - Call the NYC Department of Health hotline at 1-888-364-3065 or through 311 for NYC-specific information, or NYS Novel Coronavirus (COVID-19) Hotline: 1-888-364-3065
    - Call the NewYork-Presbyterian COVID-19 hotline at 646-697-4000 or visit https://www.nyp.org/coronavirus-information.

    Westchester County Department of Health - 914-813-5159

    CT: For up to date information on COVID-19 (the novel corona virus), you may call the Connecticut Department of Health at (860) 509-8000 or visit their website https://portal.ct.gov/Coronavirus. The local DOH for area patient is in: https://portal.ct.gov/DPH/Local-Health-Admin/LHA/Local-Health-Administration---Site-Map
** UTI .......
** rash .....
** ear pain/OM ....
** chest pain ...
** rx renewal ...
** musculoskeletal pain ...
** return to work letter ...
** radiculopathy ..
** vaginitis/other vagina ..
** testicle/penis pain ..
** N/V/D ..
** sinusitis ..
** eye complaint ..
** migraine/other HA ..
** toe discoloration .
** menopause .
** Bell's palsy .
** head injury .
** neck mass .
** coxsackie .
** hypertension .
** sore throat .
* COVID-19 Info
  CONTENTS
#+TOC: headlines 1 local :target #TargetSection
** <<covidFAQ>>OnDemand COVID FAQ
*** 1. NYP Employees Who Are Concerned They Have COVID- like illness (CLI)
    Employees who are mild to moderately ill should be advised to do home isolation for at least *7 days* from their *symptom onset date*, and they must be *fever-free for 72 hours* without the use antipyretics and their *symptoms must be improved* before returning to work. If symptomatic & at work, they should put on a mask and go home. Please see below regarding next steps.
    
     \ast{} *Source of exposure: confirmed COVID19 exposure at work ( by IPC & managers)*

     Managers will submit confirmed list under IP&amp;C guidance. WHS will contact them. If they are not contacted by WHS after 2 business days, they will need to speak with directly with their own manager.
     
     \ast{} *Source of exposure: In the community.*

     They will need a note that they sought care for CLI and they will need to call the WHS hotline for Return to Work (RTW) clearance. They should also update their mangers as well.  This note will be included as part of the discharge instructions template for NYP employees found on nexus. https://nexus.weill.cornell.edu/display/ED/COVID+Tele-medicine
     *NYP Ondemand does not provide a RTW clearance only a note that they sought care for CLI*
*** 2. NYP Employees are exposed to confirmed +COVID-19 (at work or in the community) and are WITHOUT symptoms
    They can continue to work, while the are asymptomatic. Do *NOT send them home.* Advise them to *continue to work AND wear a surgical facemask throughout entire shift.* Use same surgical facemask all shift unless soiled or wet. Advise them to do so for *14 days* counting from the *date of last exposure.*
    If they *develop symptoms* during that 14-day period, they should stay home, and call WHS. Advise them NOT to come to work/WHS even with mild symptoms.
*** 3. When may a NYP Employee return to work (RTW)
    *WHS will clear ALL employees.* Please have them call the WHS Hotline, those that have a *confirmed work exposure should received a call 2 days,* if they have community exposure or unconfirmed work exposure they should call WHS hotline.
    How does the process work. On the 8th day of symptoms, WHS staff/clinician volunteers will call to check on their clinical status for possible RTW. In order to RTW, they must be *fever-free for 72 hours* without the use antipyretics and their *symptoms must be improved.* If they are clinically well enough to be cleared by WHS over the phone, then they will be advised to wear a regular surgical face mask for the entire shift while at work for *14 days* counting from their *symptom onset date.* Patients need contact their regarding RTW status.
*** 4. How does the patient access their discharge instructions in the NOTES section in wrap up
    Have the patient go to nypondemandvisits.org on a computer rather than phone and use same password / username they used on the phone to get these notes. Have them select MY Records tab on top and select previous visits to access the discharge instructions. Patient’s that enter the system through zocdoc will not be able to see the notes. The best way to tell if a patient came in through zocdoc or the ondemand app is to ask them: &quot;how did you join us today, by the NYP app or by zocdoc?&quot;. These patients will need to create mynyp.org account. Provider them with the name and verification code given when you print invitation under Allscripts. It is found under iNYP tab and profile, you will see on right pf the screen print invitation. Click on it and it will provide the verification code and name patient will need to create an account.
*** 5. Need a note for an employer?
    Nexus page has a template that you can copy and paste into wrap up note section.
*** 6. HCW who want COVID testing
    HCP with compatible symptoms should be *assumed to have COVID-19.* WHS is *no longer doing* COVID testing.
*** 7. What Do I tell patients that wish to get tested
    NYC DOHMH recently released Advisory that patients with "COVID-like illness not requiring hospitalization should not be tested and they be instructed to stay home. It is safer for the patients and health care workers and testing does not currently change clinical management or recommendations about staying home".
*** 8. Patients Who are Concerned They Have COVID-19
    Patients who are mild to moderately ill, with COVID like symptoms, please counsel the patient that they should assume they have COVID-19. Recommend home isolation for *7 days from their symptom onset date* and until they have *72-hours without fever AND resolving symptoms*. https://www.cdc.gov/coronavirus/2019-ncov/downloads/10Things.pdf
*** 9. Discontinuation of Home Isolation
    Recommend Home isolation for *7 days* from their *symptom onset date*, they must be *fever-free for 72 hours* and their *symptoms must be improved*. *If HCW* advised to wear a regular surgical face mask while at work for *14 days* counting from their *symptom onset date.*
*** 10. Patient that are high risk that require follow up
    We will have PAs M-F during business hours, Please provide the Name , MRN, DOB and a brief summary and contact number to Covidtelefollowup@med.cornell.edu. You may also give patients the follow up number 212-746-3262
*** 11. Patients with that are dangerously ill with COVID-19 like symptoms
    Refer the patient to Emergency Department. Any patient referred to hospital, please pre-notify the hospital and give warm hand-off. (warm hand off is a transfer of care between two members of health care team).
    Patients with shortness of breath that require further evaluation should go to Emergency
room.
*** 12. How do they get to the Emergency Department
    If the patient may get there on their own, they can go in a private car or with a car service with windows down and place a mask if they have one. If the hospital is in walking distance they can also walk. Upon arrival they should notify hospital staff they have been placed on isolation for concern for COVID.  If they need 911 stay with the patient. Have them call 911 from another phone (if available) if there is no second phone, call 911 yourself and ask for help getting to the 911 operator in the area where the patient is. Notify 911 dispatcher that patient of the concern for COVID like symptoms.
*** 13. Patient calling without any symptoms
    Recommend social distancing, that should stay at home to the extent possible and only leave home for essential tasks. All New Yorkers should consider themselves as possibly exposed to COVID and must therefore self-monitor for COVID-19 like illness. 14. Patient with confirmed positive exposure and they are not a HCW Recommend self-quarantine for 14 days since the last exposure.
*** 15. Patient is anxious what resources are available
    They may contact NYC Well at 888-NYC-WELL (888-692-9355) or text WELL to 65173. NYC Well is a confidential help line that is staffed 24/7 by trained counselors who can provide brief supportive therapy, crisis counseling, and connections to behavioral health treatment, in more than 200 languages.
** Home Isolation Instructions:
   [[isolationInstructionsTarget][here]]
